#!/bin/bash

source PARAMETERS
source PROGRAMPATHS
source DIRECTORIES

REF=$1
VCFFILEN=$VCFFILENAME".vcf"

VCFFILE=$VCFDIR/$VCFFILEN

echo "Creating VCF file: $VCFFILE ..."
#$SAMTOOLS mpileup -uf $REF $IN | $BCFTOOLS call $VARCALLOPTIONS -o $VCFFILE
$FREEBAYES -f $REF $FREEBAYESOPTIONS $VCREADYDIR/*.bam > $VCFFILE
wait
echo "Done!"
echo " "

